language: node_js

sudo: false

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

os:
  - linux
  - osx
